version: '3.8'

volumes:
  farm-db:
    driver: local

networks:
  back:

services:

  farm-db:
    image: postgres:15-alpine
    hostname: farm-db
    ports:
      - "5432:5432"
    container_name: farm-db
    restart: unless-stopped
    volumes:
      - farm-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: farm_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      back:

  farm-app:
    container_name: farm-app
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - farm-db
    ports:
      - "80:8008"
    restart: on-failure
    environment:
      - POSTGRES_URL=$POSTGRES_URL
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD


