version: '3.8'

volumes:
  farm-db:
    driver: local
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:

networks:
  back:

services:

  farm-db:
    container_name: farm-db
    image: postgres:15-alpine
    hostname: farm-db
    volumes:
      - ./psql-entrypoint-initdb/:/docker-entrypoint-initdb.d/
      - farm-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: farm_db
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
#    ports:
#      - "5432"
    restart: unless-stopped
    networks:
      back:

  farm-app:
    container_name: farm-app
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - farm-db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "80:8008"
    restart: on-failure
    networks:
      back:


