version: '3.8'

volumes:
  farm-db:
    driver: local

services:

  farm-db:
    container_name: farm-db
    image: postgres:15-alpine
    hostname: farm-db
    volumes:
      - ./psql-entrypoint-initdb/:/docker-entrypoint-initdb.d/
      - farm-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: farm_db
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"
    restart: unless-stopped

  farm-app:
    container_name: farm-app
    build:
      dockerfile: Dockerfile
      context: ..
    depends_on:
      - farm-db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "80:8008"
    restart: on-failure
