name: LoC badge
on:
  push:
    branches: [ "main" ]
jobs:
  lines_counter_job:
    runs-on: ubuntu-latest
    name: A job to count lines of code
    steps:
      - uses: actions/checkout@v4
      - uses: MikhailEpatko/loc-badge-action@v2.0.0
        with:
          include-files: '.*\**'
          exclude-files: ''
      - name: Deploy badge to image-data branch
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          publish_dir: ./output
          publish_branch: loc-bage
          github_token: ${{ github.token }}
