name: open PR

on:
  pull_request:
    types:
      - opened
    branches: [ "main" ]

concurrency:
  group: main
  cancel-in-progress: true

jobs:

  tests:
    runs-on: ubuntu-latest
    needs: checkstyle
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: setup Testcontainers Cloud Client
      uses: atomicjar/testcontainers-cloud-setup-action@v1
      with:
        token: ${{ secrets.TC_CLOUD_TOKEN }}
    - name: run the Maven verify phase
      run: mvn verify
