name: Java CI/CD with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: main
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: setup Testcontainers Cloud Client
      uses: atomicjar/testcontainers-cloud-setup-action@v1
      with:
        token: ${{ secrets.TC_CLOUD_TOKEN }}
    - name: run the Maven verify phase
      run: mvn verify

  prepare-environment:
    runs-on: self-hosted
    needs: tests
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: stop and remove containers, networks
        run: sudo docker-compose down farm-app
      - name: remove unused data
        run: sudo docker system prune -a -f
        
  deploy:
    name: deploy
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: run app
        run: |
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} > .env
          echo DATABASE_USER=${{ secrets.DATABASE_USER }} > .env
          echo DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} > .env
          sudo docker-compose up -d farm-app
