name: open PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ "main" ]

concurrency:
  group: main
  cancel-in-progress: true

jobs:
  verify:
    name: Check Code Quality
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          checkstyle_config: ./checkstyle.xml
          fail_on_error: true
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  tests:
    name: Run Tests
    #    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: setup Testcontainers Cloud Client
        uses: atomicjar/testcontainers-cloud-setup-action@v1
        with:
          token: ${{ secrets.TC_CLOUD_TOKEN }}
      - name: run the Maven verify phase
        run: mvn verify
